sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: yarn
branches:
  only:
    - devel # build devel branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  verbose: true
  on:
    branch: devel
  local-dir: public